<?php
  /**
 * Add the field "spaceship" to REST API responses for posts read and write
 */
add_action( 'rest_api_init', 'slug_register_tve_content' );
function slug_register_tve_content() {
    register_rest_field( 'post',
        'tve_content',
        array(
            'get_callback'    => 'slug_get_tve_content',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );
    
    /*register_rest_field( 'post',
        'tve_images',
        array(
            'get_callback'    => 'slug_get_tve_images',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );*/
    
    register_rest_field( 'post',
        'featured_media_url',
        array(
            'get_callback'    => 'rest_api_post_featured_media_url',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );
    
    register_rest_field( 'post',
        'tve_author_name',
        array(
            'get_callback'    => 'rest_api_post_author',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );
    
    register_rest_field( 'post',
        'modified',
        array(
            'get_callback'    => 'rest_api_post_date_modified_format',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );
    
    register_rest_field( 'post',
        'modified_gmt',
        array(
            'get_callback'    => 'rest_api_post_date_modified_format',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );
    register_rest_field( 'post',
        'date',
        array(
            'get_callback'    => 'rest_api_post_date_modified_format',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );
    register_rest_field( 'post',
        'date_gmt',
        array(
            'get_callback'    => 'rest_api_post_date_modified_format',
            //'update_callback' => 'slug_update_spaceship',
            'schema'          => null,
        )
    );
}
/**
 * Handler for getting custom field data.
 *
 * @since 0.1.0
 *
 * @param array $object The object from the response
 * @param string $field_name Name of field
 * @param WP_REST_Request $request Current request
 *
 * @return mixed
 */
function slug_get_tve_content( $object, $field_name, $request ) {
    /* used ob_start to avoid any output generated by tve_editor_content) */
    ob_start();
        $all_content =  strip_tags( tve_editor_content( $object[ 'id' ], 'tcb_content' )/*, '<img>'*/ );
    ob_end_clean();
    //return nl2br( strip_tags( get_post_meta( $object[ 'id' ], 'tve_save_post', TRUE ) ) );
    return $all_content;
}

function slug_get_tve_images( $object, $field_name, $request ) {
    /* used ob_start to avoid any output generated by tve_editor_content) */
    ob_start();
    $all_content =  tve_editor_content( $object[ 'id' ], 'tcb_content' );
        // read all image tags into an array
    preg_match_all('/<img[^>]+>/i',$all_content, $imgTags); 

    for ($i = 0; $i < count($imgTags[0]); $i++) {
      // get the source string
      preg_match('/src="([^"]+)/i',$imgTags[0][$i], $imgage);

      // remove opening 'src=' tag, can`t get the regex right
      $origImageSrc[] = str_ireplace( 'src="', '',  $imgage[0]);
    }
        
    ob_end_clean();
    //return nl2br( strip_tags( get_post_meta( $object[ 'id' ], 'tve_save_post', TRUE ) ) );
    return $origImageSrc;
}

function rest_api_post_featured_media_url( $object, $field_name, $request )
{
    $image = get_the_post_thumbnail( $object['id'] );
    
    // get the source string
    preg_match('/src="([^"]+)/i',$image, $imgage);
    return str_ireplace( 'src="', '',  $imgage[0]);
}

function rest_api_post_author( $object, $field_name, $request ) {
    /* used ob_start to avoid any output generated by tve_editor_content) */
    
    //return nl2br( strip_tags( get_post_meta( $object[ 'id' ], 'tve_save_post', TRUE ) ) );
    $fname = get_the_author_meta( 'first_name' , $object['author'] );
    $lname = get_the_author_meta( 'last_name' , $object['author'] );
    $fullname = ucwords( $fname ) . ' ' . ucwords( $lname );
    
    $tmp = trim( $fname . $lname );
    if( empty( $tmp ) )
        $fullname = get_the_author_meta( 'user_nicename' , $object['author'] );
        
    return $fullname;
}

function rest_api_post_date_modified_format( $object, $field_name, $request ) {
    $formatted_date = date( "Y-m-d H:i:s", strtotime( $object[$field_name] ) );
    return $formatted_date;
}

?>
